### ISSUE TITLE
Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by jblayneyXpanxion** [APIDevTools/swagger-parser#149]
Hey There!

I have a Java Project using SpringDoc to create OpenAPI 3.0 in order to generate client code. 

Recently after I added Spring Actuator (which includes endpoints), all generation exploded with un-helpful error messages. 

What I've tried so far:
- Verified the output OpenApi json was valid json and was non-null
- Searched online for similar errors - there have been some but they've been fixed and none exactly like this one - and I'm using the latest spring libraries and maven plugins for openapi.
- Used the swagger validator and codegen tools to try to discover the issue with the spec document, but the tools explode likely due to an un-caught edge case exception flow which should be handled.
- I've narrowed the issue down to the spring boot actuator APIs that are included in the json/yml output when you configure spring doc to include the actuator endpoints in the swagger-ui.hml via config.

When you paste the json (bottom of bug) into https://apitools.dev/swagger-parser/online/  - this error shows up:

> Cannot read property 'parse' of undefined
> 
> Error: Cannot read property 'parse' of undefined
>     at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79649)
>     at parseSwagger (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231808)
>     at HTMLFormElement.<anonymous> (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231233)
>     at HTMLFormElement.dispatch (https://code.jquery.com/jquery-2.1.4.min.js:3:6466)
>     at HTMLFormElement.r.handle (https://code.jquery.com/jquery-2.1.4.min.js:3:3241)
> 
> TypeError: Cannot read property 'parse' of undefined
>     at Function.form.getAPI (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:230230)
>     at parseSwagger (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231518)
>     at HTMLFormElement.<anonymous> (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231233)
>     at HTMLFormElement.dispatch (https://code.jquery.com/jquery-2.1.4.min.js:3:6466)
>     at HTMLFormElement.r.handle (https://code.jquery.com/jquery-2.1.4.min.js:3:3241)

In my code generator, I get a similar error:

> openapi.json [0:0]: unexpected error in Open-API generation
> java.lang.NullPointerException
>     at java.util.HashSet.<init> (HashSet.java:119)
>     at org.openapitools.codegen.config.CodegenConfigurator.toContext (CodegenConfigurator.java:464)
>     at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput (CodegenConfigurator.java:507)
>     at org.openapitools.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:724)

```
{
    "components": {
        "schemas": {

            }
        }
    },
    "info": {
        "description": "Some Description",
        "license": {
            "name": "SomeApp",
            "url": "http://www.something.com"
        },
        "title": "Some API Example",
        "version": "1.1.1-SNAPSHOT"
    },
    "openapi": "3.0.1",
    "paths": {
        "/beans": {
            "get": {
                "operationId": "handle_0",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'beans'",
                "tags": [
                    "Actuator"
                ]
            }
        },
        "/health": {
            "get": {
                "operationId": "handle_1",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'health'",
                "tags": [
                    "Actuator"
                ]
            }
        },
        "/health/**": {
            "get": {
                "operationId": "handle_2",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'health-path'",
                "tags": [
                    "Actuator"
                ]
            }
        },
        "/info": {
            "get": {
                "operationId": "handle_3",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'info'",
                "tags": [
                    "Actuator"
                ]
            }
        },
        "/metrics": {
            "get": {
                "operationId": "handle_5",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'metrics'",
                "tags": [
                    "Actuator"
                ]
            }
        },
        "/metrics/{requiredMetricName}": {
            "get": {
                "operationId": "handle_4",
                "responses": {
                    "200": {
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Actuator web endpoint 'metrics-requiredMetricName'",
                "tags": [
                    "Actuator"
                ]
            }
        },
    },
    "servers": [
        {
            "description": "Generated server url",
            "url": "http://localhost:8080/api"
        }
    ],
    "tags": [
        {
            "description": "Monitor and interact",
            "externalDocs": {
                "description": "Spring Boot Actuator Web API Documentation",
                "url": "https://docs.spring.io/spring-boot/docs/current/actuator-api/html/"
            },
            "name": "Actuator"
        }
    ]
}
```

Thanks for any help!

**Comment by JamesMessinger** [comment]
Hi.  Thanks for reporting this!  It was a bug in the Swagger Parser Online website.  I really appreciate you catching it and reporting it.

The bug has been fixed now.  If you try your code sample above again, you'll still get an error, but now it's the _correct_ error and is much more informative.  It's warning you that you have an extra closing curly brace (`}`) in your JSON.

```
end of the stream or a document separator is expected at line 7, column 6:
        },
         ^

Error: end of the stream or a document separator is expected at line 7, column 6:
        },
         ^
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:79649)
    at parseSwagger (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231838)
    at HTMLFormElement.<anonymous> (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231263)
    at HTMLFormElement.dispatch (https://code.jquery.com/jquery-2.1.4.min.js:3:6466)
    at HTMLFormElement.r.handle (https://code.jquery.com/jquery-2.1.4.min.js:3:3241)

YAMLException: end of the stream or a document separator is expected at line 7, column 6:
        },
         ^
    at generateError (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:15824)
    at throwError (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:15946)
    at readDocument (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:32564)
    at loadDocuments (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:33035)
    at load (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:33272)
    at Object.safeLoad (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:33599)
    at Function.form.getAPI (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:230244)
    at parseSwagger (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231548)
    at HTMLFormElement.<anonymous> (https://apitools.dev/swagger-parser/online/js/bundle.min.js:17:231263)
    at HTMLFormElement.dispatch (https://code.jquery.com/jquery-2.1.4.min.js:3:6466)
```

**Comment by thejeff77** [comment]
Well that is good and bad news for me - good news that it is fixed! (as I probably just removed code and forgot to remove the curly brace)

But also means there is still likely an issue with the code generator for the original non-redacted version which was valid JSON. 

Somehow when I choose "Parse It" from the dropdown options on the webpage it doesn't take - still just shows "Validate It"

**Comment by JamesMessinger** [comment]
@thejeff77 - Thanks for catching yet another bug!  The "Parse It" thing should work as expected now
